name = "diary-app-sync"
main = "src/index.js"
compatibility_date = "2026-07-02"
account_id = "b1779096743d9a35527ad9f6b8aabd22"

[[d1_databases]]
binding = "DB"
database_name = "diary-app-db"
database_id = "8ccf6647-2677-42d7-96cd-462abfd2d7d2"
