name = "diary-app-sync"
main = "src/index.js"
compatibility_date = "2026-07-02"
account_id = "c8775c74e20e9761e3c0a46b9ca5a196"

[[kv_namespaces]]
binding = "KV"
id = "c91ab4efde02412eb309780d228fc627"
